### ISSUE TITLE
Other packages support?

### ISSUE THREAD

**Issue by sajqavril** [diderot-edu/diderot-guide#38]
Hi and thanks for the amazing work,
We are trying to use Diderot for the next semester, wondering if the XML compiler can support two other LaTex packages namely linguex and tipa for better involving linguistic symbols? Or, are there any other efficient way to incorporate those two packages?

Thanks,

**Comment by umutacar** [comment]
Hi Jiaqi, let's discuss this over email.  Could you please email me?
