### ISSUE TITLE
Diderot does not recognize online image URLs

### ISSUE THREAD

**Issue by gauravmm** [diderot-edu/diderot-guide#4]
When an uploaded book chapter is built from markdown with an image on an online server, for example:
```
![Regex Golf, from https://xkcd.com/1313/.  Yes, this is a real thing, see e.g. https://alf.nu/RegexGolf](http://imgs.xkcd.com/comics/regex_golf.png)
```
The web interface reports the error ` Beaming completed, but there were some issues: Attachment: regex_golf.png is missing`

**Comment by umutacar** [comment]
This is fixed.  I will deploy it to production later tonight.
